sudo: false
language: c
env:
 - BASE=3.16 STATIC=shared
 - BASE=3.16 STATIC=shared EXTRA=CMD_CXXFLAGS=-std=c++11
 - BASE=3.16 STATIC=shared CMPLR=clang
 - BASE=3.16 STATIC=static
 - BASE=3.15 STATIC=shared
 - BASE=3.14 STATIC=shared
 - BASE=3.14 STATIC=static
install: ./build-deps.sh
script:
 - make -j2 $EXTRA
